version: '3'

services:
  web:
    build: .
    command: "/bin/python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: hello_world
    volumes:
      - .:/django
    ports:
      - "8000:8000"